version: "3"

services:
  photha_nginx:
    build:
      context: ./build
      dockerfile: Dockerfile.nginx
    container_name: photha_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - photha_php
      - photha_database

  photha_php:
    build:
      context: ./build
      dockerfile: Dockerfile.php
    container_name: photha_php
    restart: always
    volumes:
      - ./src:/var/www/html:delegated
    expose:
      - "9000"

  photha_database:
    image: mariadb:10.5.8
    container_name: photha_database
    restart: always
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./database/photha_db.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: "password1234"
      MYSQL_DATABASE: photha
    expose:
      - "3306"

  photha_dba:
    depends_on:
      - photha_database
    image: phpmyadmin/phpmyadmin
    container_name: photha_dba
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: photha_database
